catalog:
  # Framework Core
  next: ^15.5.7
  react: ^19.1.2
  react-dom: ^19.1.2

  # Styling
  tailwindcss: ^4.1.18
  '@tailwindcss/postcss': ^4.1.18
  postcss: ^8.5.6

  # UI Libraries
  framer-motion: ^12.23.26
  lucide-react: ^0.454.0

  # Utilities
  clsx: ^2.1.1
  tailwind-merge: ^2.6.0
  class-variance-authority: ^0.7.1

  # Radix UI
  '@radix-ui/react-accordion': 1.2.2
  '@radix-ui/react-slot': ^1.2.4

  # Internationalization
  next-intl: ^4.6.1

  # Analytics
  posthog-js: ^1.309.1
  posthog-node: ^5.17.4

  # Development Tools
  typescript: ^5.9.2
  eslint: 9.11.1
  prettier: ^3.7.4

  # Testing
  '@playwright/test': ^1.57.0
  '@testing-library/react': ^16.3.0
  jest: ^29.7.0
  vitest: ^4.0.16

packages:
  - "apps/*"
  - "packages/*"
